homepage_route: "home"
routes:
    home: "Main:home"
    register: "User:register"
    login: "User:login"
    logout: "User:logout"
    newTwtt: "Twtt:newTwtt"
    profile: "User:profile"
    getTlProfile: "Twtt:getTlProfile"
    follow: "User:follow"